# Node.js Application with MongoDB
# Multi-container setup using library services

version: '1.0'

containers:
  sample-nodejs-datastore:
    template: ubuntu-minimal-lts
    
    # Use pre-configured MongoDB from library
    includes:
      - mongodb
    
    # MongoDB configuration via environment
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    
    # MongoDB library service provides:
    # - MongoDB installation from official repo
    # - Exposed port 27017
    # - Service setup and startup
    # - Data directory configuration

  sample-nodejs-app:
    template: ubuntu-minimal-lts
    
    # Optional: include nginx for reverse proxy
    # includes:
    #   - nginx
    
    depends_on:
      - sample-nodejs-datastore
    
    mounts:
      - ./app:/app
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    
    exposed_ports:
      - 3000    # Node.js application
    
    logs:
      - node:/var/log/node/app.log
      - node-error:/var/log/node/app_err.log
    
    tests:
      internal:
        - health:/app/tests/internal_tests.sh
      external:
        - health:/app/tests/external_tests.sh
      port_forwarding:
        - iptables:/app/tests/port_forwarding_tests.sh
    
    packages:
      - nodejs
      - npm
      - curl
      - git
    
    services:
      node:
        command: /usr/bin/node /app/server.js
        directory: /app
        autostart: true
        autorestart: true
        stdout_logfile: /var/log/node/app.log
        stderr_logfile: /var/log/node/app_err.log
        environment: NODE_ENV=development,PORT=3000,MONGO_HOST=sample-nodejs-datastore,MONGO_PORT=27017,MONGO_DB=${MONGO_DB},MONGO_USER=${MONGO_USER},MONGO_PASSWORD=${MONGO_PASSWORD}
        startsecs: 10
        stopwaitsecs: 30
    
    post_install:
      - name: "Setup Node.js directories"
        command: |
          mkdir -p /var/log/node
          mkdir -p /app/uploads
      
      - name: "Install Node.js dependencies"
        command: |
          cd /app
          npm install
      
      - name: "Test MongoDB connection"
        command: |
          # Install MongoDB client tools for testing
          apt-get update && apt-get install -y mongodb-clients
          
          # Wait for MongoDB to be ready
          echo "Testing MongoDB connection..."
          for i in $(seq 1 30); do
            if mongosh --host sample-nodejs-datastore --eval "db.version()" > /dev/null 2>&1; then
              echo "MongoDB is ready!"
              break
            fi
            echo "Waiting for MongoDB... (attempt $i/30)"
            sleep 2
          done