# Haproxy Server - Debian 12
# Haproxy on Debian 12
# Usage: lxc-compose up

version: '1.0'

containers:
  haproxy-debian-12:
    template: debian-12
    
    exposed_ports:
      - 80
      - 443
      - 8404
    
    packages:
      - haproxy
    
    tests:
      external:
        - haproxy:/tests/haproxy.sh
    
    post_install:
      - name: "Setup Haproxy"
        command: |

          # Enable and start HAProxy
          systemctl enable haproxy
          systemctl start haproxy
          
          echo "Haproxy is ready!"
