# Grafana Server - Ubuntu-Minimal 24.04
# Grafana on Ubuntu-Minimal 24.04
# Usage: lxc-compose up

version: '1.0'

containers:
  grafana-minimal-24-04:
    template: ubuntu-minimal-24.04
    
    exposed_ports:
      - 3000
    
    packages:
      - curl
      
    tests:
      external:
        - grafana:/tests/grafana.sh
    
    post_install:
      - name: "Setup Grafana"
        command: |
          # Download and install Grafana manually
          cd /tmp
          wget https://dl.grafana.com/oss/release/grafana_9.5.2_amd64.deb
          dpkg -i grafana_9.5.2_amd64.deb || apt-get install -f -y
          
          # Configure Grafana
          cat >> /etc/grafana/grafana.ini << EOF

          [server]
          http_addr = 0.0.0.0
          http_port = 3000
          EOF
          
          # Start Grafana manually
          /usr/sbin/grafana-server --config=/etc/grafana/grafana.ini --homepath=/usr/share/grafana &
          
          # Wait for Grafana to start
          sleep 10
          echo "Grafana is ready!"
    
    logs:
      - grafana:/var/log/grafana/grafana.log
