#!/bin/bash
# Manual server testing steps

SERVER="5.78.92.103"

echo "LXC Compose Server Testing Guide"
echo "================================"
echo ""
echo "Since SSH requires authentication, please run these commands manually:"
echo ""
echo "1. Connect to server:"
echo "   ssh root@$SERVER"
echo ""
echo "2. Update repository:"
echo "   cd /root/lxc-compose"
echo "   git pull origin main"
echo ""
echo "3. Test Alpine PostgreSQL with includes:"
echo "   cd examples"
echo "   lxc-compose up -f test-alpine-services.yml"
echo "   lxc-compose list"
echo "   lxc-compose test test-alpine-postgres"
echo "   lxc-compose destroy -f test-alpine-services.yml"
echo ""
echo "4. Test Ubuntu services:"
echo "   lxc-compose up -f test-ubuntu-services.yml"
echo "   lxc-compose test test-ubuntu-postgres"
echo "   lxc-compose destroy -f test-ubuntu-services.yml"
echo ""
echo "5. Test template example:"
echo "   lxc-compose up -f template-example.yml"
echo "   lxc-compose test myapp"
echo "   lxc-compose test cache"
echo "   lxc-compose destroy -f template-example.yml"
echo ""
echo "6. Test includes example:"
echo "   lxc-compose up -f includes-example.yml"
echo "   lxc-compose test webserver"
echo "   lxc-compose test database"
echo "   lxc-compose destroy -f includes-example.yml"
echo ""
echo "Key things to verify:"
echo "- Containers deploy successfully"
echo "- Tests are inherited from library services"
echo "- 'lxc-compose test <container>' runs the library service tests"
echo "- PostgreSQL CRUD tests work"
echo "- Redis operation tests work"
echo "- Nginx tests work"
echo ""
echo "Expected test output for PostgreSQL:"
echo "  ✓ PostgreSQL connection test"
echo "  ✓ Create database test"
echo "  ✓ Create table test"
echo "  ✓ Insert data test"
echo "  ✓ Query data test"
echo "  ✓ Delete data test"
echo "  ✓ Drop table test"
echo "  ✓ Drop database test"