# Mysql Server - Debian 12
# Mysql on Debian 12
# Usage: lxc-compose up

version: '1.0'

containers:
  mysql-debian-12:
    template: debian-12
    
    exposed_ports:
      - 3306
    
    packages:
      - default-mysql-server
      - default-mysql-client
    
    tests:
      external:
        - mysql:/tests/mysql.sh
    
    post_install:
      - name: "Setup Mysql"
        command: |

          # Start MySQL service
          service mysql start
          sleep 5
          
          echo "Mysql is ready!"
    
    logs:
      - mysql:/var/log/mysql/error.log
      - query:/var/log/mysql/query.log
