# Memcached Server (Docker-style)
# Simple Memcached following official Docker patterns
# Usage: lxc-compose up

version: '1.0'

containers:
  memcached:
    image: images:alpine/3.19
    
    exposed_ports:
      - 11211
    
    packages:
      - memcached
    
    tests:
      external:
        - memcached:/tests/memcached.sh
    
    post_install:
      - name: "Setup Memcached"
        command: |
          # Start memcached with common settings
          # -m: memory limit in MB
          # -c: max connections
          # -u: run as user (memcached user doesn't exist in Alpine)
          # -l: listen address
          # -p: port
          MEMCACHED_MEMORY=${MEMCACHED_MEMORY:-64}
          MEMCACHED_CONNECTIONS=${MEMCACHED_CONNECTIONS:-1024}
          
          # Start memcached as daemon
          memcached -d \
            -m $MEMCACHED_MEMORY \
            -c $MEMCACHED_CONNECTIONS \
            -l 0.0.0.0 \
            -p 11211 \
            -u nobody
          
          echo "Memcached is ready with ${MEMCACHED_MEMORY}MB memory!"