# Grafana Monitoring Dashboard (Docker-style)
# Simple Grafana following official Docker patterns
# Usage: lxc-compose up

version: '1.0'

containers:
  grafana:
    image: ubuntu:22.04
    
    exposed_ports:
      - 3000
    
    packages:
      - wget
      - gnupg
      - apt-transport-https
      - software-properties-common
    
    tests:
      external:
        - grafana:/tests/grafana.sh
    
    post_install:
      - name: "Install Grafana"
        command: |
          # Add Grafana repository
          wget -q -O - https://packages.grafana.com/gpg.key | apt-key add -
          add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
          
          # Install Grafana
          apt-get update
          apt-get install -y grafana
          
          # Configure Grafana
          sed -i 's/;http_addr =.*/http_addr = 0.0.0.0/' /etc/grafana/grafana.ini
          
          # Set admin password if provided
          GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
          sed -i "s/;admin_password =.*/admin_password = $GF_SECURITY_ADMIN_PASSWORD/" /etc/grafana/grafana.ini
          
          # Start Grafana
          systemctl enable grafana-server
          systemctl start grafana-server
          
          echo "Grafana is ready! Login: admin / $GF_SECURITY_ADMIN_PASSWORD"