# Simple Flask Application
# Ultra-lightweight using Alpine Linux

containers:
  - name: flask-app
    image: alpine:3.19
    ports:
      - "5000:5000"
    mounts:
      - source: ./
        target: /app
    services:
      - name: flask-server
        command: |
          # Install Python and dependencies
          apk add --no-cache python3 py3-pip
          
          # Setup app
          cd /app
          pip3 install flask
          
          # Create app if it doesn't exist
          if [ ! -f app.py ]; then
            cat > app.py << 'EOF'
          from flask import Flask, render_template
          import os
          
          app = Flask(__name__)
          
          @app.route('/')
          def home():
              return '''
              <html>
                  <head><title>Flask in LXC</title></head>
                  <body style="font-family: Arial; max-width: 800px; margin: 50px auto;">
                      <h1>🚀 Flask Running in Alpine Container!</h1>
                      <p>This Flask app is running in an Alpine Linux container (only ~60MB total!)</p>
                      <ul>
                          <li>Base image: Alpine 3.18 (~8MB)</li>
                          <li>Python 3 + Flask: ~50MB</li>
                          <li>Total container size: ~60MB</li>
                      </ul>
                      <p>Container hostname: ''' + os.uname()[1] + '''</p>
                  </body>
              </html>
              '''
          
          @app.route('/api/hello')
          def api_hello():
              return {'message': 'Hello from Flask in LXC!'}
          
          if __name__ == '__main__':
              app.run(host='0.0.0.0', port=5000, debug=True)
          EOF
          fi
          
          # Run the app
          python3 app.py