# Python 3 Virtual Environment Service
# Sets up Python 3 in a virtual environment at /opt/venv that acts as the system Python
# Usage: Include this service for Python applications

version: '1.0'

containers:
  python3-debian-12:
    template: debian-12
    
    packages:
      # Core Python packages
      - python3
      - python3-dev
      - python3-pip
      - python3-venv
      - python3-setuptools
      - python3-wheel
      
      # Build essentials for compiling C extensions
      - build-essential
      - gcc
      - g++
      - make
      - pkg-config
      
      # Essential libraries for common Python packages
      - libssl-dev       # Required for SSL/TLS support
      - libffi-dev       # Required for cryptography and many packages
      - zlib1g-dev       # Required for compression support
    
    environment:
      # Python environment variables
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      PIP_NO_CACHE_DIR: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      DEBIAN_FRONTEND: "noninteractive"
      # Add virtual environment to PATH
      PATH: "/opt/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      VIRTUAL_ENV: "/opt/venv"
    
    post_install:
      - name: "Setup Python virtual environment"
        command: |
          # Update package index
          apt-get update
          
          # Create virtual environment at /opt/venv
          python3 -m venv /opt/venv
          
          # Activate the virtual environment and upgrade pip
          /opt/venv/bin/python -m pip install --upgrade pip setuptools wheel
          
          # Create symlinks to make venv Python the default
          ln -sf /opt/venv/bin/python /usr/local/bin/python
          ln -sf /opt/venv/bin/python3 /usr/local/bin/python3
          ln -sf /opt/venv/bin/pip /usr/local/bin/pip
          ln -sf /opt/venv/bin/pip3 /usr/local/bin/pip3
          
          # Update profile to activate venv on login
          cat >> /etc/profile.d/python-venv.sh << 'EOF'
          # Automatically use the Python virtual environment
          export PATH="/opt/venv/bin:$PATH"
          export VIRTUAL_ENV="/opt/venv"
          EOF
          
          # Create standard directory for applications
          mkdir -p /app
          
          echo "Python 3 virtual environment ready!"
          /opt/venv/bin/python --version
          /opt/venv/bin/pip --version
    
    tests:
      internal:
        - python:/tests/python3.sh
