# Nginx Server - Ubuntu 24.04
# Nginx on Ubuntu 24.04
# Usage: lxc-compose up

version: '1.0'

containers:
  nginx-ubuntu-24-04:
    template: ubuntu-24.04
    
    exposed_ports:
      - 80
      - 443
    
    packages:
      - nginx
    
    tests:
      external:
        - nginx:/tests/nginx.sh
    
    post_install:
      - name: "Setup Nginx"
        command: |

          # Start nginx
          systemctl enable nginx
          systemctl start nginx
          
          echo "Nginx is ready!"
