# Mysql Server - Debian 11
# Mysql on Debian 11
# Usage: lxc-compose up

version: '1.0'

containers:
  mysql-debian-11:
    template: debian-11
    
    exposed_ports:
      - 3306
    
    packages:
      - default-mysql-server
      - default-mysql-client
    
    tests:
      external:
        - mysql:/tests/mysql.sh
    
    post_install:
      - name: "Setup Mysql"
        command: |

          # Start MySQL service
          service mysql start
          sleep 5
          
          echo "Mysql is ready!"
