# SearXNG settings
# See https://docs.searxng.org/admin/settings/index.html

general:
  debug: false
  instance_name: "SearXNG"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: false

brand:
  new_issue_url: https://github.com/searxng/searxng/issues/new
  docs_url: https://docs.searxng.org/
  public_instances: https://searx.space
  wiki_url: https://github.com/searxng/searxng/wiki
  issue_url: https://github.com/searxng/searxng/issues

search:
  safe_search: 0
  autocomplete: "duckduckgo"
  autocomplete_min: 4
  default_lang: "en"
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120
  suspended_times:
    SearxEngineAccessDenied: 86400
    SearxEngineCaptcha: 86400
    SearxEngineTooManyRequests: 3600
    cf_SearxEngineCaptcha: 1296000
    cf_SearxEngineAccessDenied: 86400
    recaptcha_SearxEngineCaptcha: 604800

server:
  port: 8888
  bind_address: "127.0.0.1"
  secret_key: "changeme_use_openssl_rand_hex_16"
  base_url: false
  image_proxy: true
  http_protocol_version: "1.0"
  method: "POST"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

redis:
  url: redis://127.0.0.1:6379/0

ui:
  static_path: ""
  templates_path: ""
  default_theme: simple
  default_locale: ""
  query_in_title: false
  infinite_scroll: false
  center_alignment: false
  cache_url: https://web.archive.org/web/
  results_on_new_tab: false
  theme_args:
    simple_style: auto

# Preferences defaults
preferences:
  lock:
    - autocomplete
    - safesearch
    - theme
    - method

# Output formats
outgoing:
  request_timeout: 3.0
  useragent_suffix: ""
  pool_connections: 100
  pool_maxsize: 20
  enable_http2: true

# Result proxy
result_proxy:
  url: null
  key: null
  proxify_results: false

# Categories
categories_as_tabs:
  general:
  images:
  videos:
  news:
  music:
  files:
  science:

# Engines configuration
engines:
  - name: google
    engine: google
    shortcut: go
    disabled: false

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false

  - name: bing
    engine: bing
    shortcut: bi
    disabled: false

  - name: qwant
    engine: qwant
    shortcut: qw
    disabled: false

  - name: startpage
    engine: startpage
    shortcut: sp
    disabled: false

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false

  - name: github
    engine: github
    shortcut: gh
    disabled: false

  - name: stackoverflow
    engine: stackoverflow
    shortcut: st
    disabled: false

  - name: reddit
    engine: reddit
    shortcut: re
    disabled: false

  - name: youtube
    engine: youtube_noapi
    shortcut: yt
    disabled: false

# Hostname replacements
hostname_replace: {}

# Enabled plugins
enabled_plugins:
  - 'Hash plugin'
  - 'Self Information'
  - 'Tracker URL remover'
  - 'Ahmia blacklist'

# Disabled plugins
disabled_plugins:
  - 'Hostname replace'