# Grafana Server - Alpine 3.19
# Grafana on Alpine 3.19
# Usage: lxc-compose up

version: '1.0'

containers:
  grafana-alpine-3-19:
    template: alpine-3.19
    
    exposed_ports:
      - 3000
    
    packages:
      - curl
    tests:
      external:
        - grafana:/tests/grafana.sh
    
    post_install:
      - name: "Setup Grafana"
        command: |
          # Install Grafana on Alpine
          cd /tmp
          wget https://dl.grafana.com/oss/release/grafana-9.5.2.linux-amd64.tar.gz
          tar -xzf grafana-9.5.2.linux-amd64.tar.gz
          mv grafana-9.5.2 /opt/grafana
          
          # Create grafana user
          adduser -D -h /opt/grafana grafana
          chown -R grafana:grafana /opt/grafana
          
          # Configure Grafana
          cat > /opt/grafana/conf/custom.ini << EOF
          [server]
          http_addr = 0.0.0.0
          http_port = 3000

          [security]
          admin_user = admin
          admin_password = admin
          EOF
          
          # Create startup script
          cat > /usr/local/bin/start-grafana.sh << 'SCRIPT'
          #!/bin/sh
          cd /opt/grafana
          su - grafana -c "/opt/grafana/bin/grafana-server --config=/opt/grafana/conf/custom.ini --homepath=/opt/grafana"
          SCRIPT
          chmod +x /usr/local/bin/start-grafana.sh
          
          # Start Grafana in background
          nohup /usr/local/bin/start-grafana.sh > /var/log/grafana.log 2>&1 &
          
          # Wait for Grafana to start
          sleep 10
          echo "Grafana is ready!"
    
    logs:
      - grafana:/var/log/grafana/grafana.log
