# Supervisor Process Management Service for ubuntu-22.04
# Provides supervisor for managing long-running processes
# Usage: Automatically included when services are defined

version: '1.0'

containers:
  supervisor-ubuntu-22-04:
    template: ubuntu-22.04
    
    packages:
      - supervisor      # Process management system
    
    post_install:
      - name: "Setup Supervisor"
        command: |
          # Create default supervisor directories
          mkdir -p /etc/supervisor/conf.d /var/log/supervisor
          
          # Update supervisor configuration to use conf.d
          if ! grep -q "files = /etc/supervisor/conf.d/\*.conf" /etc/supervisor/supervisord.conf; then
            cat >> /etc/supervisor/supervisord.conf << 'CONF'
          
          [include]
          files = /etc/supervisor/conf.d/*.conf
          CONF
          fi
          
          # Create environment variable loading script
          cat > /usr/local/bin/load-env.sh << 'EOF'
          #!/bin/bash
          # Load environment variables from .env file for all supervised processes
          if [ -f /app/.env ]; then
              set -a  # automatically export all variables
              source /app/.env
              set +a  # turn off automatic export
          fi
          exec "$@"
          EOF
          chmod +x /usr/local/bin/load-env.sh
          
          # Ensure supervisor can run without systemd
          # Create a startup script for non-systemd environments
          cat > /usr/local/bin/start-supervisor << 'SCRIPT'
          #!/bin/bash
          /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
          SCRIPT
          chmod +x /usr/local/bin/start-supervisor
          
          # Enable supervisor auto-start
          systemctl enable supervisor
          
          echo "Supervisor configured successfully"
    
    tests:
      internal:
        - supervisor:/tests/supervisor.sh
