# Django with PostgreSQL and Redis - Alpine Linux Version
# Ultra-lightweight deployment using Alpine Linux (~8MB base)
# Note: Alpine uses musl libc, which may have compatibility issues with some Python packages

containers:
  # Database and cache server using Alpine
  django-alpine-datastore:
    image: alpine:3.19
    services:
      - name: setup-services
        command: |
          # Install PostgreSQL and Redis
          apk add --no-cache postgresql postgresql-client redis
          
          # Initialize PostgreSQL
          mkdir -p /run/postgresql
          chown postgres:postgres /run/postgresql
          su postgres -c "initdb -D /var/lib/postgresql/data"
          
          # Configure PostgreSQL
          echo "host all all 10.0.3.0/24 md5" >> /var/lib/postgresql/data/pg_hba.conf
          echo "listen_addresses = '*'" >> /var/lib/postgresql/data/postgresql.conf
          
          # Start PostgreSQL
          su postgres -c "pg_ctl -D /var/lib/postgresql/data -l /var/lib/postgresql/logfile start"
          sleep 5
          
          # Create database and user
          su postgres -c "createdb djangodb"
          su postgres -c "psql -c \"CREATE USER djangouser WITH PASSWORD 'djangopass';\""
          su postgres -c "psql -c \"GRANT ALL PRIVILEGES ON DATABASE djangodb TO djangouser;\""
          
          # Configure and start Redis
          sed -i 's/bind 127.0.0.1/bind 0.0.0.0/g' /etc/redis.conf
          sed -i 's/protected-mode yes/protected-mode no/g' /etc/redis.conf
          redis-server /etc/redis.conf

  # Django application server using Alpine
  django-alpine-app:
    image: alpine:3.19
    ports:
      - "8001:8000"  # Django dev server
    services:
      - name: django-setup
        command: |
          # Install Python and dependencies
          apk add --no-cache python3 py3-pip python3-dev \
            gcc musl-dev linux-headers \
            postgresql-dev postgresql-client \
            nginx build-base libffi-dev
          
          # Setup Python environment
          mkdir /app
          cd /app
          pip install --upgrade pip
          pip install django psycopg2 redis celery gunicorn
          
          # Create Django project if it doesn't exist
          if [ ! -f manage.py ]; then
            django-admin startproject myproject .
            mv /app/settings.py /app/myproject/settings.py
          
            # Wait for database to be ready
            sleep 10

            # Run migrations
            python manage.py migrate
            python manage.py collectstatic --noinput || true
          fi

          # Start Django development server
          python manage.py runserver 0.0.0.0:8000