# Haproxy Server - Debian 11
# Haproxy on Debian 11
# Usage: lxc-compose up

version: '1.0'

containers:
  haproxy-debian-11:
    template: debian-11
    
    exposed_ports:
      - 80
      - 443
      - 8404
    
    packages:
      - haproxy
    
    tests:
      external:
        - haproxy:/tests/haproxy.sh
    
    post_install:
      - name: "Setup Haproxy"
        command: |

          # Enable and start HAProxy
          systemctl enable haproxy
          systemctl start haproxy
          
          echo "Haproxy is ready!"
    
    logs:
      - haproxy:/var/log/haproxy.log
