# Prometheus Server - Ubuntu-Minimal 24.04
# Prometheus on Ubuntu-Minimal 24.04
# Usage: lxc-compose up

version: '1.0'

containers:
  prometheus:
    image: ubuntu-minimal:24.04
    
    exposed_ports:
      - 9090
    
    packages:

    
    tests:
      external:
        - prometheus:/tests/prometheus.sh
    
    post_install:
      - name: "Setup Prometheus"
        command: |
# TODO: Implement for this base image
          
          echo "Prometheus is ready!"
