# Prometheus Server - Ubuntu-Minimal 24.04
# Prometheus on Ubuntu-Minimal 24.04
# Usage: lxc-compose up

version: '1.0'

containers:
  prometheus-minimal-24-04:
    template: ubuntu-minimal-24.04
    
    exposed_ports:
      - 9090
    
    packages:
      - curl
      - wget

    tests:
      external:
        - prometheus:/tests/prometheus.sh
    
    post_install:
      - name: "Setup Prometheus"
        command: |
          # Install Prometheus manually
          cd /tmp
          wget https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz
          tar -xzf prometheus-2.45.0.linux-amd64.tar.gz
          mv prometheus-2.45.0.linux-amd64 /opt/prometheus
          
          # Create prometheus user
          useradd -r -s /bin/false prometheus || true
          chown -R prometheus:prometheus /opt/prometheus
          
          # Basic configuration
          cat > /opt/prometheus/prometheus.yml << EOF
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
              - targets: ['localhost:9090']
          EOF
          
          # Start Prometheus
          sudo -u prometheus /opt/prometheus/prometheus --config.file=/opt/prometheus/prometheus.yml --storage.tsdb.path=/opt/prometheus/data &
          
          # Wait for Prometheus to start
          sleep 5
          echo "Prometheus is ready!"
    
    logs:
      - prometheus:/opt/prometheus/prometheus.log
