# Prometheus Server - Alpine 3.19
# Prometheus on Alpine 3.19
# Usage: lxc-compose up

version: '1.0'

containers:
  prometheus-alpine-3-19:
    template: alpine-3.19
    
    exposed_ports:
      - 9090
    
    packages:
      - curl
    tests:
      external:
        - prometheus:/tests/prometheus.sh
    
    post_install:
      - name: "Setup Prometheus"
        command: |
          # Install Prometheus on Alpine
          cd /tmp
          wget https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz
          tar -xzf prometheus-2.45.0.linux-amd64.tar.gz
          mv prometheus-2.45.0.linux-amd64 /opt/prometheus
          
          # Create prometheus user
          adduser -D -h /opt/prometheus prometheus
          chown -R prometheus:prometheus /opt/prometheus
          
          # Basic configuration
          cat > /opt/prometheus/prometheus.yml << EOF
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
              - targets: ['localhost:9090']
          EOF
          
          # Create startup script
          cat > /usr/local/bin/start-prometheus.sh << 'SCRIPT'
          #!/bin/sh
          cd /opt/prometheus
          su - prometheus -c "/opt/prometheus/prometheus --config.file=/opt/prometheus/prometheus.yml --storage.tsdb.path=/opt/prometheus/data"
          SCRIPT
          chmod +x /usr/local/bin/start-prometheus.sh
          
          # Start Prometheus in background
          nohup /usr/local/bin/start-prometheus.sh > /var/log/prometheus.log 2>&1 &
          
          # Wait for Prometheus to start
          sleep 5
          echo "Prometheus is ready!"
    
    logs:
      - prometheus:/opt/prometheus/prometheus.log
