# /srv/lxc-compose/configs/database.yaml
container:
  name: database
  template: database-template
  ip: 10.0.3.2

services:
  postgres:
    version: 15
    port: 5432
    data_dir: /var/lib/postgresql/data
    configs:
      max_connections: 200
      shared_buffers: 256MB
    
  redis:
    version: 7
    port: 6379
    persistence: true
    maxmemory: 2gb
    maxmemory_policy: allkeys-lru

mounts:
  - host: /srv/shared/database/postgres
    container: /var/lib/postgresql/data
  - host: /srv/shared/database/redis
    container: /var/lib/redis
  - host: /srv/logs/database
    container: /var/log/app

logging:
  rotation: daily
  keep_days: 7
  centralized: true
  path: /srv/logs/database