# Mysql Server - Ubuntu-Minimal 22.04
# Mysql on Ubuntu-Minimal 22.04
# Usage: lxc-compose up

version: '1.0'

containers:
  mysql-minimal-22-04:
    template: ubuntu-minimal-22.04
    
    exposed_ports:
      - 3306
    
    packages:
      - mysql-server
      - mysql-client
    
    tests:
      external:
        - mysql:/tests/mysql.sh
    
    post_install:
      - name: "Setup Mysql"
        command: |

          # Start MySQL service
          service mysql start
          sleep 5
          
          echo "Mysql is ready!"
