# Mongodb Server - Alpine 3.19
# Mongodb on Alpine 3.19
# Usage: lxc-compose up

version: '1.0'

containers:
  mongodb-alpine-3-19:
    template: alpine-3.19
    
    exposed_ports:
      - 27017
    
    packages:
      - mongodb
      - mongodb-tools
    tests:
      external:
        - mongodb:/tests/mongodb.sh
    
    post_install:
      - name: "Setup Mongodb"
        command: |
          # Configure and start MongoDB
          # Create data directory
          mkdir -p /data/db
          chown mongodb:mongodb /data/db
          
          # Create config file
          cat > /etc/mongod.conf << EOF
          storage:
            dbPath: /data/db
          net:
            bindIp: 0.0.0.0
            port: 27017
          EOF
          
          # Start MongoDB
          mongod --config /etc/mongod.conf --fork --logpath /var/log/mongodb.log
          
          # Wait for MongoDB to start
          sleep 5
          
          # Test connection
          mongo --eval "db.version()" || echo "MongoDB starting..."
          echo "Mongodb is ready!"
    
    logs:
      - mongodb:/var/log/mongodb.log
