# Nginx Server - Ubuntu-Minimal 22.04
# Nginx on Ubuntu-Minimal 22.04
# Usage: lxc-compose up

version: '1.0'

containers:
  nginx-minimal-22-04:
    template: ubuntu-minimal-22.04
    
    exposed_ports:
      - 80
      - 443
    
    packages:
      - nginx
    
    tests:
      external:
        - nginx:/tests/nginx.sh
    
    post_install:
      - name: "Setup Nginx"
        command: |

          # Start nginx
          systemctl enable nginx
          systemctl start nginx
          
          echo "Nginx is ready!"
    
    logs:
      - access:/var/log/nginx/access.log
      - error:/var/log/nginx/error.log
