# Rabbitmq Server - Alpine 3.19
# Rabbitmq on Alpine 3.19
# Usage: lxc-compose up

version: '1.0'

containers:
  rabbitmq-alpine-3-19:
    template: alpine-3.19
    
    exposed_ports:
      - 5672
      - 15672
    
    packages:
      - rabbitmq-server
    tests:
      external:
        - rabbitmq:/tests/rabbitmq.sh
    
    post_install:
      - name: "Setup Rabbitmq"
        command: |
          # Configure and start RabbitMQ
          # Enable management plugin
          rabbitmq-plugins enable rabbitmq_management
          
          # Start RabbitMQ
          rc-service rabbitmq-server start
          rc-update add rabbitmq-server default
          
          # Wait for RabbitMQ to start
          sleep 10
          
          # Create admin user
          rabbitmqctl add_user admin admin || true
          rabbitmqctl set_user_tags admin administrator || true
          rabbitmqctl set_permissions -p / admin ".*" ".*" ".*" || true
          echo "Rabbitmq is ready!"
    
    logs:
      - rabbitmq:/var/log/rabbitmq/rabbit.log
      - startup:/var/log/rabbitmq/startup_log
