# Nginx Server - Debian 11
# Nginx on Debian 11
# Usage: lxc-compose up

version: '1.0'

containers:
  nginx:
    image: images:debian/11
    
    exposed_ports:
      - 80
      - 443
    
    packages:
      - nginx
    
    tests:
      external:
        - nginx:/tests/nginx.sh
    
    post_install:
      - name: "Setup Nginx"
        command: |

          # Start nginx
          systemctl enable nginx
          systemctl start nginx
          
          echo "Nginx is ready!"
