# Grafana Server - Ubuntu 24.04
# Grafana on Ubuntu 24.04
# Usage: lxc-compose up

version: '1.0'

containers:
  grafana:
    template: ubuntu-24.04
    
    exposed_ports:
      - 3000
    
    packages:
      - wget
      - gnupg
      - apt-transport-https
      - software-properties-common

    
    tests:
      external:
        - grafana:/tests/grafana.sh
    
    post_install:
      - name: "Setup Grafana"
        command: |

          # Add Grafana repository
          wget -q -O - https://packages.grafana.com/gpg.key | apt-key add -
          add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
          apt-get update
          
          # Install Grafana
          apt-get install -y grafana
          
          # Configure
          sed -i 's/;http_addr =.*/http_addr = 0.0.0.0/' /etc/grafana/grafana.ini
          
          # Set admin password
          GF_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
          sed -i "s/;admin_password =.*/admin_password = $GF_ADMIN_PASSWORD/" /etc/grafana/grafana.ini
          
          # Start Grafana
          systemctl enable grafana-server
          systemctl start grafana-server
          echo "Grafana is ready!"
