# Python 3 Virtual Environment Service for ubuntu-22.04
# Sets up Python 3 in a virtual environment at /opt/venv that acts as the system Python
# Usage: Include this service for Python applications

version: '1.0'

containers:
  python3-ubuntu-22-04:
    template: ubuntu-22.04
    
    packages:
      # Core Python packages
      - python3
      - python3-dev
      - python3-pip
      - python3-venv
      - python3-setuptools
      - python3-wheel
      
      # Build essentials for compiling C extensions
      - build-essential
      - gcc
      - g++
      - make
      - pkg-config
      
      # Essential libraries for common Python packages
      - libssl-dev       # Required for SSL/TLS support
      - libffi-dev       # Required for cryptography and many packages
      - zlib1g-dev       # Required for compression support
    
    environment:
      # Python environment variables
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      PIP_NO_CACHE_DIR: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      DEBIAN_FRONTEND: "noninteractive"
      # Add virtual environment to PATH
      PATH: "/opt/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      VIRTUAL_ENV: "/opt/venv"
    
    post_install:
      - name: "Setup Python virtual environment"
        command: |
          # Update package index
          apt-get update
          
          # Create virtual environment at /opt/venv
          python3 -m venv /opt/venv
          
          # Activate the virtual environment and upgrade pip
          /opt/venv/bin/python -m pip install --upgrade pip setuptools wheel
          
          # Create wrapper scripts that use the venv Python
          cat > /usr/local/bin/python << 'WRAPPER'
          #!/bin/sh
          exec /opt/venv/bin/python "$@"
          WRAPPER
          chmod +x /usr/local/bin/python
          
          cat > /usr/local/bin/python3 << 'WRAPPER'
          #!/bin/sh
          exec /opt/venv/bin/python3 "$@"
          WRAPPER
          chmod +x /usr/local/bin/python3
          
          cat > /usr/local/bin/pip << 'WRAPPER'
          #!/bin/sh
          exec /opt/venv/bin/pip "$@"
          WRAPPER
          chmod +x /usr/local/bin/pip
          
          cat > /usr/local/bin/pip3 << 'WRAPPER'
          #!/bin/sh
          exec /opt/venv/bin/pip3 "$@"
          WRAPPER
          chmod +x /usr/local/bin/pip3
          
          # Update profile to set environment variables
          cat >> /etc/profile.d/python-venv.sh << 'EOF'
          # Set Python virtual environment variables
          export PATH="/opt/venv/bin:$PATH"
          export VIRTUAL_ENV="/opt/venv"
          PYTHONVERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
          export PYTHONPATH="/opt/venv/lib/python${PYTHONVERSION}/site-packages:$PYTHONPATH"
          EOF
          
          # Create standard directory for applications
          mkdir -p /app
          
          echo "Python 3 virtual environment ready!"
          /opt/venv/bin/python --version
          /opt/venv/bin/pip --version
    
    tests:
      internal:
        - python:/tests/python3.sh
